parse_resume_task:
  description: >
    Clean this resume text quickly \n\n{truncated_text}\n\n.
    Remove artifacts, normalize bullets to '-', keep all content. Be fast and direct.
  expected_output: >
    Clean resume text with proper structure.
  agent: parser_agent

rewrite_for_ats_task:
  description: >
    Rewrite resume for a given job.
    Match keywords, use action verbs, add metrics. Target 80+ ATS score. Be direct and fast.
  expected_output: >
    ATS-optimized resume with keyword placement and metrics.
  agent: ats_writer_agent

refine_bullets_task:
  description: >
    Polish these bullets with action verbs and metrics.
    Add strong verbs and numbers. Be fast and direct.
  expected_output: >
    Resume with enhanced bullet points and metrics.
  agent: refiner_agent

evaluate_ats_task:
  description: >
    Score a resume for a given job.
    Rate 1-5: keywords, structure, metrics, verbs, format.
    Return JSON with overall_score (0-100), breakdown, missing_keywords, quick_wins.
  expected_output: >
    JSON evaluation with scores and recommendations.
  agent: evaluator_agent

general_question_task:
  description: >
    Given the candidate’s resume, generate 5 general interview questions exploring career journey, strengths, and overall experience.
    Questions should be open-ended, not role-specific, and avoid technical depth.
  expected_output: >
    5 open-ended general interview questions that help understand the candidate’s background.
  agent: general_question_agent

managerial_question_task:
  description: >
    Based on the resume, generate 5 tough managerial questions focusing on leadership, decision-making, conflict resolution, and client management.
    Questions should assess leadership skills and handling pressure.
  expected_output: >
    5 challenging managerial questions exploring leadership and stakeholder management.
  agent: managerial_question_agent

hr_question_task:
  description: >
    Using the resume as context, generate 5 HR questions exploring motivation, cultural fit, salary expectations, career aspirations, and work preferences.
    Avoid technical details.
  expected_output: >
    5 HR questions about motivation, culture fit, and career goals.
  agent: hr_question_agent

behavioral_question_task:
  description: >
    Given the resume, generate 5 STAR-based behavioral questions focusing on past challenges, team interactions, and problem-solving.
  expected_output: >
    5 behavioral interview questions based on Situation, Task, Action, Result framework.
  agent: behavioral_question_agent

technical_question_task:
  description: >
    Based on the candidate’s resume, generate 5 challenging technical questions tailored to their skills and domain.
    Focus on applied knowledge and scenario-based answers.
  expected_output: >
    5 technical questions that test problem-solving and applied knowledge.
  agent: technical_question_agent
